# Define the conda python environment
name: py_dsa
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - scipy
  - networkx
  - pip
  - matplotlib
  - seaborn
  - pandas
  - nltk
    
